#!/bin/sh

OLD_URL=$1
NEW_URL=$2

if [ -z "${OLD_URL}" ] || [ -z "${NEW_URL}" ]; then
  swagger-diff
  exit 1
fi

OLD_FILE="old.json"
NEW_FILE="new.json"

[ -f "${OLD_FILE}" ] && rm -f "${OLD_FILE}" && [ -f "${NEW_FILE}" ] && rm -f "${NEW_FILE}"

wget -q -O "${OLD_FILE}" "${OLD_URL}" && wget -q -O "${NEW_FILE}" "${NEW_URL}"

if [ ! -f "${OLD_FILE}" ]; then
  echo "'${OLD_URL}' is not downloaded!"
  exit 1
fi

if [ ! -f "${NEW_FILE}" ]; then
  echo "'${NEW_URL}' is not downloaded!"
  exit 1
fi

swagger-diff "${OLD_FILE}" "${NEW_FILE}"
